### ISSUE TITLE
グローバルナビゲーションのcurrentが重複している

### ISSUE THREAD

**Issue by contiki9** [webbingstudio/acms_theme_echo_zero#1]
![image](https://cloud.githubusercontent.com/assets/6760605/24078835/05e17560-0cbc-11e7-9af6-b4950d44c34a.png)
---
http://cms-skill.com/echo_zero_demo/docs/customize/first/import_full.html

導入手順に入ると解説資料にもcurrentのラインが入っていますが仕様でしたでしょうか？

**Comment by webbingstudio** [comment]
はい、こちらは規定通りの動作となります。
ナビゲーションのハイライトは、a-blog cmsの組み込みJSライブラリ「link match location」を利用しています。
https://developer.a-blogcms.jp/reference/latest/builtinjs/index.html#link_match_location

これは表示中のページのURL内に、各ナビゲーションのリンクが含まれている場合にハイライトします。

導入手順のページのURLは下記ですが
（ルートブログのURL）docs/customize/first/import_full.html
このページは解説資料のカテゴリに含まれているページですから
（ルートブログのURL）docs/
両方ともハイライトすることになります。
