### ISSUE TITLE
お問い合わせの必須入力を入れても判定が通らない

### ISSUE THREAD

**Issue by contiki9** [webbingstudio/acms_theme_echo_zero#2]
![image](https://cloud.githubusercontent.com/assets/6760605/24092128/9dd54814-0d8f-11e7-8888-02012e86ff3b.png)

---

必須入力の項目をすべて入れてもエラーメッセージが表示されて確認画面に遷移でないケースがありました。
※住所の項目を入力すると確認画面に遷移できました。

ご確認お願いできますでしょうか。

**Comment by contiki9** [comment]
https://twitter.com/webbingstudio/status/843760412407418880
```
@maki_saki GitHubのissueの必須入力の件、名前を漢字で入力したらどうなりますか？今日はもう作業してないもので、推測ですみません。どっちにしてもフォームオプションを見直します。ありがとうございます。
```
漢字で入力しても駄目でした。

**Comment by webbingstudio** [comment]
@contiki9 すみません！都道府県と住所が必須扱いになっていました！
お手数ですが、下記ファイルを差し替えていただけますか。
dist/themes/echo_zero/contact/form/input.html
