### ISSUE TITLE
「Tweets by #」と表示される件について

### ISSUE THREAD

**Issue by contiki9** [webbingstudio/acms_theme_echo_zero#3]
テーマを適応するとフッターに「Tweets by #」と表示されるのに気が付きました。
想定外の表示かと思いご報告。

該当HTML
```
<div class="section social-plugins">
<div class="row">
<div class="col-xs-12">
<div class="m-b-lg-sm p-x-md-sm">
<a class="twitter-timeline" data-lang="ja" data-theme="light" data-height="500" href="https://twitter.com/#">Tweets by #</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
```

## 補足
CMSにtwitterのIDを登録していません。

## 環境
- version 1.2.0
- CMSver 2.6.1.3 / Standard
- URLはhttps

---
![image](https://cloud.githubusercontent.com/assets/6760605/25928135/6aa3cdca-3635-11e7-8a5d-d4848f684e96.png)

---
不足の情報があれば、提供したいと思います。

**Comment by webbingstudio** [comment]
Twitterアカウントが空だと、これは出てこないはずので、以下をご確認いただけますか。

- 管理ページ「ブログ」の設定を更新してみてください。
- Twitterアカウントの欄に、半角スペースが入っていないでしょうか？
- IFブロックの誤動作も考えられます。 /dist/themes/echo_zero/include/parts/social_plugins.html を開いて、Facebookページのパーツを削除して更新してみるとどうなるでしょうか。

**Comment by contiki9** [comment]
早々のご確認ありがとうございます。

大変すみません。原因は下記でした。
> Twitterアカウントの欄に、半角スペースが入っていないでしょうか？

文字列を削除したら「Tweets by #」が表示されなくなりました。。
お手数をおかけして申し訳ないです。
